language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - build-tools-26.0.1
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
script:
  - ./gradlew test